services:
  app:
    build: .
    ports:
      - "3000:3000"

  db:
    image: postgres:18.0-alpine3.22
    restart: always
    # set shared memory limit when using docker compose
    shm_size: 128mb
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: tbd
